# Generated by Django 5.0.2 on 2024-03-16 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QA_Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Enter a rating between 1 and 5')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('km_driven', models.PositiveIntegerField(default=0)),
                ('location_link', models.URLField()),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_available', models.BooleanField(default=False, verbose_name='EMI Available')),
                ('description', models.TextField()),
                ('district', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_app.district')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.fueltype')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_of_gear', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_app.geartype', verbose_name='Type of Gear')),
                ('type_of_owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_app.ownertype', verbose_name='Type of Owner')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.vehiclebrand')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.vehicletype')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.year')),
            ],
        ),
        migrations.CreateModel(
            name='RentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('location_link', models.URLField()),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_driven', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('district', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_app.district')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.fueltype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_vehicles', to=settings.AUTH_USER_MODEL)),
                ('type_of_gear', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_app.geartype', verbose_name='Type of Gear')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.vehiclebrand')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.vehicletype')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.year')),
            ],
        ),
    ]
